name: Typst

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        required: true

jobs:
  build:
    name: Compile PDF
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Typst
        run: |
          DIST=typst-x86_64-unknown-linux-musl
          wget https://github.com/typst/typst/releases/download/v0.13.0/$DIST.tar.xz
          tar -xf $DIST.tar.xz
          cd $DIST
          mv typst /usr/local/bin/

      - name: Compile PDF
        run: |
          mkdir -p build
          typst compile source/main.typ build/thesis.pdf

      - uses: actions/upload-artifact@v4
        with:
          name: thesis-pdf
          path: build/thesis.pdf
          retention-days: 3

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: thesis-pdf
          path: build/thesis.pdf

      - name: ls
        run: ls && ls build

      - uses: softprops/action-gh-release@v2
        with:
          files: build/thesis.pdf
          tag_name: ${{ github.event.inputs.tag }}
